# Site settings
title: 'Les Cast Codeurs Podcast'
url: 'https://lescastcodeurs.com'
podcast_url: 'https://traffic.libsyn.com/lescastcodeurs'
author:
  name: 'Les Cast Codeurs'
  email: 'commentaire@lescastcodeurs.com'
  twitter: 'lescastcodeurs'
description: >-
  Les Cast Codeurs est un podcast en français de, par et pour les développeurs. Prenez connaissance des dernières nouvelles de la sphère Java et du
  développement en général. Plongez sur un sujet précis avec les épisodes interview.
lang: 'fr'
locale: 'fr_FR' # jekyll-seo-tag
date_format: '%d/%m/%Y'

feed:
  posts_limit: 10000

collections:
  - 'team'

header_pages:
  - path: 'equipe.html'
  - path: 'concept.md'
  - path: 'participer.md'
  - path: 'soutenir.md'
  - path: 'episodes.html'
    title: 'Rechercher'
    icon: 'search'

sidebar_cards:
  - name: 'Nous soutenir'
    links:
      - name: 'Patreon'
        icon: 'piggy-bank-fill'
        color: 'piggy-pink'
        url: 'https://www.patreon.com/LesCastCodeurs'
#      - name: 'Sondage 2024'
#        icon: 'chat-dots'
#        color: 'black'
#        url: 'https://lescastcodeurs.com/sondage'
  - name: 'Syndication'
    links:
      - name: 'Liste des épisodes'
        icon: 'music-note-list'
        color: 'black'
        file: 'episodes.html'
      - name: 'Feed'
        icon: 'rss-fill'
        color: 'rss-orange'
        url: 'https://lescastcodeurs.com/podcast-rss'
      - name: 'YouTube'
        icon: 'youtube'
        color: 'youtube-red'
        url: 'https://www.youtube.com/@lescastcodeurs'
      - name: 'iTunes'
        icon: 'music-note-beamed'
        color: 'apple-podcast-violet'
        url: 'https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewPodcast?id=312239675'
  - name: 'Contacts'
    links:
      - name: 'lescastcodeurs.com'
        icon: 'bluesky'
        color: 'twitter-blue'
        url: 'https://bsky.app/profile/lescastcodeurs.com'
      - name: '@lescastcodeurs'
        icon: 'twitter-x'
        color: 'black'
        url: 'https://twitter.com/lescastcodeurs'
      - name: 'Ask Me Anything'
        icon: 'chat-dots'
        color: 'black'
        url: 'https://lescastcodeurs.com/ama'
      - name: 'Crowdcast'
        icon: 'mic-fill'
        color: 'mic-grey'
        file: 'crowdcasting.md'
      - name: 'Email'
        icon: 'envelope-fill'
        color: 'black'
        url: 'mailto:commentaire@lescastcodeurs.com'
  - name: 'Discuter'
    links:
      - name: 'Google groups'
        icon: 'chat-dots'
        color: 'google-group-blue'
        url: 'https://groups.google.com/group/lescastcodeurs'

defaults:
  - scope:
      path: ""
    values:
      image: /images/default-twitter-card.png
  # jekyll-sitemap - excludes
  - scope:
      path: "presentations/"
    values:
      sitemap: false

# Build settings
encoding: 'utf-8'
timezone: 'Europe/Paris'
permalink: '/:year/:month/:day/:title/'
paginate: 10
paginate_path: "/page/:num"

plugins:
  - 'jekyll-paginate'
  - 'jekyll-seo-tag'
  - 'jekyll-sitemap'

exclude:
  - '.idea'
  - '.jekyll-cache/'
  - '.sass-cache/'
  - 'CONTRIBUTING.md'
  - 'bin'
  - 'gemfiles/'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'node_modules/'
  - 'LICENSE'
  - 'README.md'
  - 'vendor/bundle/'
  - 'vendor/cache/'
  - 'vendor/gems/'
  - 'vendor/ruby/'
