# Site settings
title: 'Les Cast Codeurs Podcast'
url: 'https://lescastcodeurs.com'
podcast_url: 'https://traffic.libsyn.com/lescastcodeurs'
author:
  name: 'Les Cast Codeurs'
  email: 'commentaire@lescastcodeurs.com'
  twitter: 'lescastcodeurs'
description: >-
  Les Cast Codeurs est un podcast en français de, par et pour les développeurs. Prenez connaissance des dernières nouvelles de la sphère Java et du
  développement en général. Plongez sur un sujet précis avec les épisodes interview.
lang: 'fr'
locale: 'fr_FR' # jekyll-seo-tag
date_format: '%d/%m/%Y'

feed:
  posts_limit: 10000

collections:
  - 'team'

header_pages:
  - path: 'equipe.html'
  - path: 'concept.md'
  - path: 'crowdcasting.md'
  - path: 'soutenir.md'
  - path: 'episodes.html'
    title: 'Rechercher'
    icon: 'search'

sidebar_cards:
  - name: 'Nous soutenir'
    links:
      - name: 'Patreon'
        icon: 'piggy-bank-fill'
        color: 'piggy-pink'
        url: 'https://www.patreon.com/LesCastCodeurs'
  - name: 'Syndication'
    links:
      - name: 'Liste des épisodes'
        icon: 'music-note-list'
        color: 'black'
        file: 'episodes.html'
      - name: 'Feed'
        icon: 'rss-fill'
        color: 'rss-orange'
        url: 'https://lescastcodeurs.com/podcast-rss'
      - name: 'iTunes'
        icon: 'music-note-beamed'
        color: 'apple-podcast-violet'
        url: 'https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewPodcast?id=312239675'
      - name: 'Licence'
        icon: 'files'
        color: 'black'
        file: 'licence.md'
  - name: 'Contacts'
    links:
      - name: 'Email'
        icon: 'envelope-fill'
        color: 'black'
        url: 'mailto:commentaire@lescastcodeurs.com'
      - name: '@lescastcodeurs'
        icon: 'twitter'
        color: 'twitter-blue'
        url: 'https://twitter.com/lescastcodeurs'
      - name: 'Crowdcast'
        icon: 'mic-fill'
        color: 'mic-grey'
        file: 'crowdcasting.md'
  - name: 'Discuter'
    links:
      - name: 'Google groups'
        icon: 'chat-dots'
        color: 'google-group-blue'
        url: 'https://groups.google.com/group/lescastcodeurs'

google_analytics: 'UA-3479508-5'
disqus:
  shortname: 'lescastcodeurs'

defaults:
  # jekyll-sitemap - excludes
  - scope:
      path: "presentations/"
    values:
      sitemap: false

# Build settings
encoding: 'utf-8'
timezone: 'Europe/Paris'
permalink: '/:year/:month/:day/:title/'
paginate: 10
paginate_path: "/page/:num"

dependencies:
  css:
    - name: 'bootstrap.min.css'
      href: 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css'
      integrity: 'sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY='
    - name: 'bootstrap-icons.css'
      href: 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css'
      integrity: 'sha256-rzXMaro05QBd53CZ36ctTBp3FdKN3Ow0P0gDHcjLCLw='
  scripts:
    - name: 'jquery.slim.min.js'
      src: 'https://code.jquery.com/jquery-3.5.1.slim.min.js'
      integrity: 'sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj'
    - name: 'bootstrap.bundle.min.js'
      src: 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js'
      integrity: 'sha256-fgLAgv7fyCGopR/gBNq2iW3ZKIdqIcyshnUULC4vex8='
    - name: 'simple-jekyll-search.min.js'
      src: 'https://cdn.jsdelivr.net/npm/simple-jekyll-search@1.9.2/dest/simple-jekyll-search.min.js'
      integrity: 'sha256-ieUctArvXa2Jaww7u+OyjqzBpOW04E9K17BzP8qrxVM='

plugins:
  - 'jekyll-paginate'
  - 'jekyll-seo-tag'
  - 'jekyll-sitemap'

exclude:
  - '.idea'
  - '.jekyll-cache/'
  - '.sass-cache/'
  - 'CONTRIBUTING.md'
  - 'bin'
  - 'gemfiles/'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'node_modules/'
  - 'LICENSE'
  - 'README.md'
  - 'vendor/bundle/'
  - 'vendor/cache/'
  - 'vendor/gems/'
  - 'vendor/ruby/'
