# Site settings
title: 'Les Cast Codeurs Podcast'
author: 'Les Cast Codeurs'
email: 'commentaire@lescastcodeurs.com'
description: >-
  Les Cast Codeurs est un podcast en français de, par et pour les développeurs. Prenez connaissance des dernières nouvelles de la sphère Java et du
  développement en général. Plongez sur un sujet précis avec les épisodes interview.
baseurl: ''
url: 'https://lescastcodeurs.com/'
twitter_username: 'lescastcodeurs'
github_username:  'lescastcodeurs'

# Build settings
theme: 'minima'
plugins:
  - 'jekyll-feed'
exclude:
  - '.idea'
  - '.jekyll-cache/'
  - '.sass-cache/'
  - 'gemfiles/'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'node_modules/'
  - 'LICENSE'
  - 'vendor/bundle/'
  - 'vendor/cache/'
  - 'vendor/gems/'
  - 'vendor/ruby/'
